name: Build
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  stubs:
    name: NorthstarStubs
    runs-on: ubuntu-latest
    container: docker.io/library/alpine:3.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          apk add mingw-w64-gcc meson
          meson setup --cross-file misc/mingw-w64-cross.txt --prefix / build
          meson install -C build --destdir destdir

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NorthstarStubs
          path: build/destdir/bin/*.dll
          if-no-files-found: error
